### ISSUE TITLE
为什么对v-for循环里面的图片不起效果？

### ISSUE THREAD

**Issue by yexinjia** [826327700/vue-photo-preview#19]
有什么解决办法吗？

**Comment by DrakLu** [comment]
没有人解答吗？？？？？

**Comment by ys930126** [comment]
> 有什么解决办法吗？

> 没有人解答吗？？？？？

代码 show一下，因为插件满足先注册后使用的规则。
你的v-for 一定是在远端获取的接口数据后，然后进行循环吧。
你必须等你的v-for中的元素完全遍历后再开始调用 $previewRefresh()

**Comment by DrakLu** [comment]
ok解决了，谢谢！！！！
