### ISSUE TITLE
图片预览弹框层级太低

### ISSUE THREAD

**Issue by dengxiaozhen** [826327700/vue-photo-preview#20]
在和`element-ui`使用时，由于`element-ui`本身有`dialog`组件。使得`图片预览弹框`会被`element-ui` 的`dialog`挡住
![1541313640844](https://user-images.githubusercontent.com/8529528/47961140-cf488d00-e03f-11e8-94ba-b1e34aa88f1b.jpg)

**Comment by ys930126** [comment]
可以在 当前Dilalog 的  <style> 中 使用 z-index 提高 层级
```
<style>
// 用于将相册图片展开时强制放在页面最顶层
.pswp{
  z-index: 150000;
}
</style>

```

**Comment by dengxiaozhen** [comment]
@ys930126 我试过这样的写法，是无效的

**Comment by dengxiaozhen** [comment]
@ys930126 样式是局部作用域下是无效的

**Comment by todayis-aha** [comment]
你好，我目前也遇到这种问题，请问有什么好的解决办法吗？

**Comment by erekook** [comment]
.el-image-viewer__wrapper {
  z-index: 999999 !important;
}

放在全局css里

**Comment by OnlY0226** [comment]
这个可以解决
https://blog.csdn.net/qq_61402485/article/details/131202117
