### ISSUE TITLE
请问：有没有API手动触发查看大图，应为有很多场景不是点击图片查看大图的

### ISSUE THREAD

**Issue by xiaoyexiang** [826327700/vue-photo-preview#59]
请问：有没有API手动触发查看大图，应为有很多场景不是点击图片查看大图的？

场景：后台返回的是html字符串，在vue里面需要v-html，里面的图片也希望能触发查看大图

**Comment by tangsiwen** [comment]
同问

**Comment by xiaoyexiang** [comment]
我自己查看源码后发现实现的原理是通过```'img[preview]'```选择器来操作DOM进行图片预览。
So.
我通过正则在每一个```img```标签插进```preview=nnn```nnn 是你想要的数字，这样就可以实现。
不过还是需要用户手动触发点击事件，通过API触发还不行

**Comment by Hanggeen** [comment]
可以试试在标签上模拟点击事件：
document.querySelector("img[preview='1']").click()
